//! Cross-implementation test vectors for [`canonical_id`].
//!
//! These vectors are generated by the reference Python `_nostr_event_id`
//! implementation. The Rust port must produce byte-identical output for
//! identical input — any divergence is a bug in this crate.
//!
//! Regeneration: see the comment block above each constant.

use signet_protocol::{canonical_id, AUTH_EVENT_KIND, CREDENTIAL_KIND};

/// Test vector generated from the Python reference impl with:
///   pubkey      = "b" * 64  (i.e. 32 bytes of 0xbb)
///   created_at  = 1_700_000_000
///   kind        = 21236
///   tags        = [["challenge", "a"*64], ["origin", "https://localhost:8094"]]
///   content     = ""
///
/// Lock value: regenerate via `tools/website/auth.py:_nostr_event_id` in the
/// signet ecosystem and reconcile if this fails. A failure here means a
/// Rust / TS divergence — both impls must match before either is shipped.
#[test]
fn auth_event_id_matches_reference_impl() {
    const REFERENCE_HEX: &str = "f0affcce500eead3b7eca8181250a8fd439e4c7b978ab4fd89627c6c9845bd51";

    let pubkey = [0xbbu8; 32];
    let tags = vec![
        vec!["challenge".to_string(), "a".repeat(64)],
        vec!["origin".to_string(), "https://localhost:8094".to_string()],
    ];

    let id = canonical_id(&pubkey, 1_700_000_000, AUTH_EVENT_KIND, &tags, "");
    assert_eq!(hex::encode(id), REFERENCE_HEX);
}

/// Empty tags + non-empty content vector. Locks the integer serialisation
/// (no trailing `.0`) and the empty-array handling.
#[test]
fn empty_tags_with_content_is_stable() {
    let pubkey = [0u8; 32];
    let id_a = canonical_id(&pubkey, 1_700_000_000, AUTH_EVENT_KIND, &[], "hello");
    let id_b = canonical_id(&pubkey, 1_700_000_000, AUTH_EVENT_KIND, &[], "hello");
    assert_eq!(id_a, id_b);
}

/// Pubkey + kind sensitivity — flipping any input changes the id.
#[test]
fn id_changes_when_any_input_changes() {
    let baseline = canonical_id(&[0u8; 32], 1, AUTH_EVENT_KIND, &[], "");
    let diff_pubkey = canonical_id(&[1u8; 32], 1, AUTH_EVENT_KIND, &[], "");
    let diff_ts = canonical_id(&[0u8; 32], 2, AUTH_EVENT_KIND, &[], "");
    let diff_kind = canonical_id(&[0u8; 32], 1, CREDENTIAL_KIND, &[], "");
    let diff_content = canonical_id(&[0u8; 32], 1, AUTH_EVENT_KIND, &[], " ");

    assert_ne!(baseline, diff_pubkey);
    assert_ne!(baseline, diff_ts);
    assert_ne!(baseline, diff_kind);
    assert_ne!(baseline, diff_content);
}

#[test]
fn kind_constants_match_signet_spec() {
    assert_eq!(AUTH_EVENT_KIND, 21236);
    assert_eq!(CREDENTIAL_KIND, 31000);
}
